import Head from 'next/head'
import { useRef } from 'react'
import Navbar from '../components/Navbar'
import Main from '../components/Main'
import About from '../components/About'
import Skills from '../components/Skills'
import Education from '../components/Education'
import Experience from '../components/Experience'
import NavProvider from '../context/NavContext'
import Contact from '../components/Contact'

export default function Home() {
  const main = useRef(null);
  const about = useRef(null);
  const education = useRef(null);
  const experience = useRef(null);
  const skills = useRef(null);
  //const projects = useRef(null);
  const contact = useRef(null);


  return (
    <div className='h-screen scrollbar-thin scrollbar-track-slate-400/25 scrollbar-thumb-red-400/75'>
      <Head>
        <title>Chris Johanson | Fullstack SWE</title>
        <meta name="My personal site" content="Generated by create next app" />
        <link rel="icon" href={`${process.env.NEXT_PUBLIC_FAVICON}/favicon.ico`} />
      </Head>
      
      <NavProvider>
      <Navbar />
      <section id='homeSection' ref={main}>
        <Main />
      </section>
      <section id='aboutSection' ref={about}>
        <About />
      </section>
      <section id='educationSection' ref={education}>
        <Education />
      </section>
      <section id='experienceSection' ref={experience}>
        <Experience/>
      </section>
      <section id='skillsSection' ref={skills}>
        <Skills />
      </section>
      <section id='contactSection' ref={contact}>
        <Contact />
      </section>
      </NavProvider>

      <footer>
        
      </footer>
    </div>
  )
}
